
from django.urls import path, include

from rest_framework.routers import DefaultRouter

from .views import UserViewSet, TaskViewSet, PermissionViewSet

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

# Create a router instance.
router = DefaultRouter()

# Register our ViewSets with the router.
# The router will automatically generate the URLs for us.
# For example, 'tasks' will create '/api/tasks/' (for listing/creating) and '/api/tasks/<id>/' (for retrieving/updating/deleting).
router.register(r'users', UserViewSet)
router.register(r'tasks', TaskViewSet)
router.register(r'permissions', PermissionViewSet)

# The urlpatterns list defines the final URLs.
urlpatterns = [
    # This includes all the URLs generated by our router.
    path('', include(router.urls)),
    # This adds the URL for getting a new token (logging in).
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    # This adds the URL for refreshing an existing token.
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

